project:
  type: website

website:
  title: "Jargon Company"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sources.qmd
      - ent_company.qmd
      - team.qmd
      - faq.qmd

format:
  html:
    theme: [cyborg]
    css: styles.css
    toc: true



